=== PeWeProxy/adaptive-proxy-plugins-core/plugins/webimp/WebpageStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="website">
        <xs:complexType>
            <xs:sequence>
            	<xs:element name="content" maxOccurs="unbounded">
                	<xs:complexType>
                		<xs:sequence>
		                	<xs:element name="tag" type="xs:string"/>
		                	<xs:element name="type" type="xs:string"/>
		                	<xs:element name="value" type="xs:string"/>
	                	</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="footer" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="header" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>                                  
                <xs:element name="logo" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>                
                <xs:element name="menuLeft" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuLeftHeading" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuLeftItems" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuRight" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuRightHeading"  minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuRightItems" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuTop" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuTopHeading" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuTopItems" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuBottom" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuBottomHeading" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="menuBottomItems" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>
                <xs:element name="news" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
		                	<xs:element name="type" type="xs:string"/>
		                	<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>	
                </xs:element>                
                <xs:element name="print" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>                
                <xs:element name="search" minOccurs="0" maxOccurs="1">
                	<xs:complexType>
                		<xs:sequence>
                			<xs:element name="tag" type="xs:string"/>
                			<xs:element name="type" type="xs:string"/>
                			<xs:element name="value" type="xs:string"/>
                		</xs:sequence>
                	</xs:complexType>
                </xs:element>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PeWeProxy/adaptive-proxy-plugins-core/conf/stubaStructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WebpageStructure.xsd">
  <menuRight>
  	<tag>div</tag>
  	<type>id</type>
  	<value>content_right</value>
  </menuRight>
  <print>
  	<tag>div</tag>
  	<type>class</type>
  	<value>print_button</value>
  </print>
  <content>
    <tag>div</tag>
    <type>class</type>
    <value>content_text</value>
  </content>  
</website>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/webimp/stubaStructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WebpageStructure.xsd">
	<content>
    	<tag>div</tag>
    	<type>class</type>
    	<value>content_text</value>
  	</content>
  	<footer>
  		<tag>div</tag>
  		<type>id</type>
  		<value>footer</value>
  	</footer>
  	<header>
  		<tag>div</tag>
  		<type>id</type>
  		<value>top</value>
  	</header>
  	<logo>
  		<tag>div</tag>
  		<type>class</type>
  		<value>logo</value>
  	</logo>
	<menuLeft>
		<tag>div</tag>
  		<type>id</type>
  		<value>content_left</value>
	</menuLeft>
	<menuLeftHeading>
		<tag>div</tag>
  		<type>class</type>
  		<value>box_nadpis</value>
	</menuLeftHeading>	
	<menuLeftItems>
		<tag>div</tag>
		<type>class</type>
		<value>box</value>
	</menuLeftItems>
	<menuRight>
		<tag>div</tag>
		<type>id</type>
		<value>content_right</value>
	</menuRight>
	<menuRightHeading>
		<tag>div</tag>
  		<type>class</type>
  		<value>box_nadpis</value>
	</menuRightHeading>
	<menuRightItems>
		<tag>div</tag>
		<type>class</type>
		<value>box</value>
	</menuRightItems>
	<menuTop>
		<tag>div</tag>
  		<type>class</type>
  		<value>top_menu</value>
	</menuTop>	
	<news>
	 	<tag>div</tag>
	 	<type>class</type>
	 	<value>news_annotation</value>
	 </news>
	<print>
		<tag>div</tag>
		<type>class</type>
		<value>print_button</value>
	</print>
	<search>
		<tag>div</tag>
		<type>class</type>
		<value>box_search</value>
	</search> 
</website>
