=== PeWeProxy/adaptive-proxy-plugins-core/plugins/PluginConfiguration.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT plugin (name, classLocation?, className, libraries?, types, parameters?)>

<!--
	The name of the plugin. This text is used for plugin identification. If there is
	plugin with the same name already loaded, the name uniqueness check is repeated
	with new names in format
		'name#NUM'					(without the quotation marks)
	where NUM is the integer starting at 0 and increased at each iteration by 1, until
	the new unique name is found.
-->
<!ELEMENT name (#PCDATA)>

<!--
	Plugin's classes class-path. Can point to either directory or a jar file. If
	there's no such element, default path pointing to plugin's home directory
	(configured by pluginsHome parameter in AdaptiveEngine section of proxy conf file)
	is used.
-->
<!ELEMENT classLocation (#PCDATA)>

<!--
	Name of the plugin's class - class implementing ProxyPlugin interface with zero
	argument constructor.
-->
<!ELEMENT className (#PCDATA)>

<!--
	Plugin's dependencies class-paths. Each subelement can point to either directory or
	jar file. ClassLoader loading this plugin's class will also be able to load classes
	from these paths.
-->
<!ELEMENT libraries (lib*)>
<!ELEMENT lib (#PCDATA)>

<!--
	Types of the plugin. Subelements text values need to be be one of these:
		RequestProcessingPlugin
		ResponseProcessingPlugin
		RequestServicePlugin
		ResponseServicePlugin
		CloseEventPlugin
		TimeoutEventPlugin
		FailureEventPlugin
	or the plugin won't be used by the proxy.
-->
<!ELEMENT types (type*)>
<!ELEMENT type (#PCDATA)>

<!--
	Configuration parameters. May be omitted. Subelements are in format
		<param name="KEY">VALUE</param>
-->
<!ELEMENT parameters (param*)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
  name		CDATA	#REQUIRED
>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/ProcessingPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>ProcessingPlugin</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.user.ProcessingPlugin</className>
	<types>
		<type>RequestProcessingPlugin</type>
		<type>ResponseProcessingPlugin</type>
	</types>
	<parameters>
		<param name="scriptUrl">${baseurl}/javascripts/recognizeUser.js</param>
		<param name="bypassPattern">userRecognitionRequest.html</param>
		<param name="generateResponse">true</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/BifrostBypassService.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>BifrostBypassService</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.injector.JavaScriptInjectingProcessingPlugin</className>
	<types>
		<type>RequestProcessingPlugin</type>
		<type>ResponseProcessingPlugin</type>
	</types>
	<parameters>
		<param name="scriptUrl"></param>
		<param name="bypassPattern">bifrost/negativefeedback</param>
		<param name="bypassTo">http://peweproxy.fiit.stuba.sk/recommendations/negative</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/HtmlInjectorService.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>HtmlInjectorService</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.injector.HtmlInjectorServiceModule</className>
	<types>
		<type>ResponseServiceModule</type>
	</types>
	<parameters>
		<param name="endOfBodyExceptions">http://(?:www\.)?google\..*</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/RelationalDBLoggingBackendServiceModule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>RelationalDBLoggingBackendServiceModule</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.logging.backends.RelationalDBLoggingBackend</className>
	<types>
		<type>RequestServiceModule</type>
		<type>ResponseServiceModule</type>
	</types>
	<parameters>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/UIDRemoverProcessingPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>UIDRemoverProcessingPlugin</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.user.UIDRemoverProcessingPlugin</className>
	<types>
		<type>RequestProcessingPlugin</type>
	</types>
	<parameters>
		<param name="exception">${baseurl}</param>
		<param name="pattern">__peweproxy_uid=</param>
		<param name="header">Cookie</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/ActivityUpdaterPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>ActivityUpdaterPlugin</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.injector.JavaScriptInjectingProcessingPlugin</className>
	<types>
		<type>RequestProcessingPlugin</type>
		<type>ResponseProcessingPlugin</type>
	</types>
	<parameters>
		<param name="scriptUrl">http://peweproxy.fiit.stuba.sk/javascripts/timelog.js</param>
		<param name="bypassPattern">activity/update</param>
		<param name="bypassTo">http://peweproxy.fiit.stuba.sk/activity/update</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/SetupJavaScriptEnvironmentProcessingPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>SetupJavaScriptEnvironmentProcessingPlugin</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.injector.SetupJavaScriptEnvironmentProcessingPlugin</className>
	<types>
		<type>ResponseProcessingPlugin</type>
	</types>
	<parameters>
		<param name="jQueryPath">${plugins-core:assets-path}/jquery-1.5.2.js</param>
		<param name="peweproxyPath">${plugins-core:assets-path}/peweproxy.js</param>
	</parameters>
</plugin>

=== PeWeProxy/adaptive-proxy-plugins-core/plugins/UIDFromCookiePlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "PluginConfiguration.dtd">
<plugin>
	<name>UIDFromCookiePlugin</name>
	<classLocation/>
	<className>sk.fiit.rabbit.adaptiveproxy.plugins.services.user.UIDFromCookiePlugin</className>
	<types>
		<type>RequestProcessingPlugin</type>
		<type>ResponseProcessingPlugin</type>
	</types>
	<parameters>
		<param name="scriptUrl">${baseurl}/set_cookie/cookie.js</param>
		<param name="bypassPattern">${baseurl}/set_cookie/cookie.js</param>
		<param name="generateResponse">true</param>
		<param name="cookieDomain">${baseurl}</param>
	</parameters>
</plugin>
